# Generated by Django 2.2.7 on 2020-03-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
    ]
