# Generated by Django 3.0.4 on 2020-10-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200325_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
